import styles from "./index.module.css";
import Head from "next/head";
import useIsLogged from "~/hooks/useIsLogged";
import SignIn from "~/components/SignIn";
import Layout from "~/components/Layout";
import Homepage from "~/components/Homepage";
export default function Home() {
    const logged = useIsLogged();
    if (!logged) {
        return <SignIn />;
    }
    return (
        <>
            <Head>
                <title>Postify</title>
                <meta name='description' content='Generated by create-t3-app' />
                <link rel='icon' href='/favicon.ico' />
            </Head>
            <Layout>
                <Homepage />
            </Layout>
        </>
    );
}
