import { signIn } from "next-auth/react";
import Layout from "./Layout";
import { Box, Button, Paper, Typography } from "@mui/material";
import GitHubIcon from "@mui/icons-material/GitHub";
import Head from "next/head";
const SignIn: React.FC = () => {
    return (
        <Layout>
            <Head>
                <title>Sign in - Postify</title>
                <meta name='description' content='Generated by create-t3-app' />
                <link rel='icon' href='/favicon.ico' />
            </Head>
            <Box
                sx={{
                    display: "flex",
                    flexDirection: "column",
                    height: "100vh",
                    alignItems: "center",
                    mt: 12,
                    p: 3,
                }}>
                <Paper
                    elevation={4}
                    sx={{
                        display: "flex",
                        flexDirection: "column",
                        alignItems: "center",
                        gap: 3,
                        p: 2,
                    }}>
                    <Typography variant='h2'> Welcome to Postify!</Typography>
                    <Typography variant='h6'>
                        You have to login to use this site.
                    </Typography>
                    <Button
                        variant='outlined'
                        startIcon={<GitHubIcon />}
                        onClick={() => void signIn()}
                        className='btn-primary btn'
                        sx={{
                            backgroundColor: "#000000",
                            color: "#fff",
                            borderColor: "#000000",
                            width: 300,
                            "&:hover": {
                                backgroundColor: "#333030",
                                borderColor: "#2a2b2d",
                                boxShadow: "none",
                            },
                        }}>
                        Sign In
                    </Button>
                </Paper>
            </Box>
        </Layout>
    );
};
export default SignIn;
